# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+g0f1ab7e.d20230222'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'g0f1ab7e.d20230222')
